/// Catalog of reflection scenarios — 45 scenarios (9 per mood).
///
/// Ported verbatim from the Android Kotlin source
/// (`com.gpstracker.routiny.reflection.ReflectionScenarios`).
/// All Arabic text is preserved exactly.
///
/// ignore_for_file: unused_import
import 'reflection_models.dart';

class ReflectionScenario {
  final String moodId;
  final Set<String> matchFeelings; // feeling ids
  final Set<String> matchInfluences; // influence ids
  final List<String> dayDescription; // 3 lines
  final String insight;
  final String advice;
  final List<String> routine; // 4 items
  final String supportMessage;

  const ReflectionScenario({
    required this.moodId,
    required this.matchFeelings,
    required this.matchInfluences,
    required this.dayDescription,
    required this.insight,
    required this.advice,
    required this.routine,
    required this.supportMessage,
  });
}

const reflectionScenarios = <ReflectionScenario>[
  // ═══════════ رائعة 😄 ═══════════
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'happy', 'grateful', 'calm'},
    matchInfluences: {'family', 'routine'},
    dayDescription: [
      'اليوم كان مريح وقلبي هادي 🤍',
      'وجود الناس اللي بحبهم فرق معايا 😊',
      'حاسة براحة نفسية جميلة 😌',
    ],
    insight: 'أنتِ في حالة سلام وامتنان داخلي.',
    advice: 'استمتعي باللحظات البسيطة ومتستعجليش الأيام.',
    routine: ['كتابة امتنان', 'وقت هدوء', 'مشروب دافي', 'نوم منتظم'],
    supportMessage: 'الراحة اللي جواكي نعمة تستحقيها 🤍',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'proud', 'excited', 'strong'},
    matchInfluences: {'achievement', 'work'},
    dayDescription: [
      'إنجاز صغير خلاني فخورة ✨',
      'عندي طاقة أكمل أكتر 🤩',
      'حاسة إني قادرة على حاجات كتير 💪',
    ],
    insight: 'ثقتك بنفسك بدأت تزيد بسبب مجهودك.',
    advice: 'احتفلي بأي تقدم حتى لو بسيط.',
    routine: ['To-do صغيرة', 'استراحة بين المهام', 'مكافأة بسيطة', 'تقليل التشتت'],
    supportMessage: 'أنتِ أقوى مما تتخيلي فعلًا ✨',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'loved', 'content', 'happy'},
    matchInfluences: {'relationships', 'friends'},
    dayDescription: [
      'وجود الناس الصح مريحني 🥰',
      'قلبي أخف النهارده 🙂',
      'حاسة بحب واهتمام 😊',
    ],
    insight: 'الأمان العاطفي بيأثر على مودك جدًا.',
    advice: 'قربي من الناس اللي يطمنوك نفسيًا.',
    routine: ['قعدة لطيفة', 'مكالمة مع شخص قريب', 'موسيقى هادية', 'وقت بعيد عن الضغط'],
    supportMessage: 'وجودك مريح وجميل للي حواليك 🥰',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'inspired', 'happy', 'hopeful'},
    matchInfluences: {'hobby', 'learning'},
    dayDescription: [
      'أفكاري ماشية بشكل جميل 💡',
      'عندي رغبة أبدأ حاجات جديدة 🌱',
      'حاسة بطاقة حلوة 😊',
    ],
    insight: 'الجانب الإبداعي عندك نشيط جدًا اليوم.',
    advice: 'سجلي أفكارك قبل ما تضيع.',
    routine: ['كتابة أفكار', 'ممارسة هواية', 'وقت هدوء', 'تقليل المشتتات'],
    supportMessage: 'طاقتك الحلوة واضحة جدًا ✨',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'excited', 'strong', 'proud'},
    matchInfluences: {'exercise', 'achievement'},
    dayDescription: [
      'الحركة حسنت مودّي جدًا 🤩',
      'حاسة بطاقة وقوة 💪',
      'فخورة بنفسي النهارده ✨',
    ],
    insight: 'النشاط والحركة انعكسوا بشكل إيجابي على نفسيتك.',
    advice: 'استمري في أي نشاط يحسسك بالحيوية.',
    routine: ['رياضة خفيفة', 'ميه كفاية', 'أكل صحي', 'نوم بدري'],
    supportMessage: 'أنتِ بتخلقي طاقتك الحلوة بنفسك ✨',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'grateful', 'calm', 'loved'},
    matchInfluences: {'family', 'gratitude'},
    dayDescription: [
      'حاسة بدفا جميل حواليا 🥰',
      'قلبي هادي ومبسوط 😌',
      'ممتنة للحاجات البسيطة 🤍',
    ],
    insight: 'أنتِ في حالة رضا داخلي لطيفة جدًا.',
    advice: 'حافظي على اللحظات اللي بتحسسك بالأمان.',
    routine: ['وقت عائلي', 'أكل بتحبيه', 'هدوء قبل النوم', 'كتابة شعورك'],
    supportMessage: 'القلب الهادي ده يستحق الراحة دائمًا 🤍',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'happy', 'hopeful', 'content'},
    matchInfluences: {'nature', 'weather'},
    dayDescription: [
      'الجو محسسني براحة 🌱',
      'يوم بسيط لكنه لطيف 😊',
      'حاسة بهدوء نفسي جميل 🙂',
    ],
    insight: 'أنتِ متصالحة مع نفسك أكتر اليوم.',
    advice: 'استغلي الأيام الهادية في شحن طاقتك.',
    routine: ['تمشية بسيطة', 'مشروب دافي', 'موسيقى هادية', 'نوم منتظم'],
    supportMessage: 'الهدوء اللي جواكي جميل فعلًا 🤍',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'proud', 'loved', 'inspired'},
    matchInfluences: {'relationships', 'achievement'},
    dayDescription: [
      'حاسة إني متقدرة من اللي حواليا 🥰',
      'فخورة بنفسي ومجهودي ✨',
      'عندي طاقة إيجابية جميلة 💡',
    ],
    insight: 'الاهتمام والتقدير بيأثروا فيكي بشكل كبير.',
    advice: 'كملي في الطريق اللي محسسك بقيمتك.',
    routine: ['مشاركة إنجازاتك', 'وقت مع ناس مريحة', 'كتابة أفكارك', 'تقليل الضغط'],
    supportMessage: 'أنتِ تستحقي كل شعور حلو بتحسيه 🤍',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'calm', 'happy', 'strong'},
    matchInfluences: {'routine', 'achievement'},
    dayDescription: [
      'يوم منظم ومريح 😌',
      'الإنجاز البسيط فرق معايا 😊',
      'حاسة بثقة وراحة 💪',
    ],
    insight: 'الاستقرار والإنجاز بيخلوا نفسيتك أفضل.',
    advice: 'كملي خطوة خطوة بدون ضغط كبير.',
    routine: ['تنظيم يومك', 'تحديد هدف صغير', 'وقت راحة', 'نوم كفاية'],
    supportMessage: 'أنتِ ماشية بشكل رائع فعلًا ✨',
  ),

  // ═══════════ جيدة 🙂 ═══════════
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'calm', 'grateful', 'content'},
    matchInfluences: {'routine', 'weather'},
    dayDescription: [
      'اليوم هادي ومريح نفسيًا 😌',
      'فيه سلام داخلي بسيط 🤍',
      'الروتين المستقر مطمني 🙂',
    ],
    insight: 'أنتِ محتاجة استقرار وراحة أكتر من الإثارة.',
    advice: 'كملي على العادات الصغيرة اللي مريحاكي.',
    routine: ['مشروب دافي', 'ترتيب بسيط', 'قراءة خفيفة', 'نوم منتظم'],
    supportMessage: 'الهدوء النفسي نعمة كبيرة فعلًا 🤍',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'happy', 'hopeful', 'inspired'},
    matchInfluences: {'learning', 'achievement'},
    dayDescription: [
      'عندي رغبة أطور نفسي 🌱',
      'الإنجاز الصغير فرق معايا 😊',
      'حاسة بإلهام وطاقة حلوة 💡',
    ],
    insight: 'فيه حماس داخلي للنمو والتغيير الإيجابي.',
    advice: 'استثمري طاقتك في خطوة حقيقية صغيرة.',
    routine: ['To-do بسيطة', 'ساعة تعلم', 'تقليل التشتت', 'مكافأة بسيطة'],
    supportMessage: 'كل خطوة صغيرة بتقربك لنسختك الأفضل ✨',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'loved', 'content', 'happy'},
    matchInfluences: {'relationships', 'friends'},
    dayDescription: [
      'وجود الناس الصح مطمني 🥰',
      'قلبي مرتاح أكتر النهارده 🙂',
      'حاسة باحتواء جميل 😊',
    ],
    insight: 'أنتِ تتأثري جدًا بالحب والاهتمام الحقيقي.',
    advice: 'اقضي وقت أكتر مع الأشخاص اللي يريحوك.',
    routine: ['مكالمة لطيفة', 'قعدة مع حد قريب', 'موسيقى هادية', 'وقت بعيد عن السوشيال'],
    supportMessage: 'وجودك لطيف ومريح للي حواليك 🥰',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'proud', 'excited', 'strong'},
    matchInfluences: {'achievement', 'work'},
    dayDescription: [
      'حاسة إني أنجزت حاجة مهمة ✨',
      'عندي حماس أكمل أكتر 🤩',
      'فخورة بالمجهود اللي عملته 💪',
    ],
    insight: 'ثقتك بنفسك بدأت تزيد بسبب تعبك الحقيقي.',
    advice: 'احتفلي بأي إنجاز حتى لو بسيط.',
    routine: ['تحديد هدف صغير', 'تنظيم الوقت', 'راحة بين المهام', 'مكافأة لنفسك'],
    supportMessage: 'أنتِ أقوى مما تتخيلي فعلًا ✨',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'calm', 'neutral', 'grateful'},
    matchInfluences: {'nature', 'weather'},
    dayDescription: [
      'اليوم بسيط لكنه مريح 😌',
      'بحاول أعيش بهدوء أكتر 🤍',
      'مفيش ضغط كبير النهارده 😶',
    ],
    insight: 'أنتِ بتحاولي تحافظي على توازنك النفسي.',
    advice: 'الراحة مش كسل… دي احتياج.',
    routine: ['تمشية بسيطة', 'تنفس ببطء', 'وقت هدوء', 'تقليل الضوضاء'],
    supportMessage: 'أنتِ تستحقي السلام النفسي 🤍',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'inspired', 'hopeful', 'proud'},
    matchInfluences: {'hobby', 'learning'},
    dayDescription: [
      'أفكاري متدفقة بشكل جميل 💡',
      'عندي أمل وحماس للفترة الجاية 🌱',
      'حاسة بفخر تجاه نفسي ✨',
    ],
    insight: 'الجانب الإبداعي عندك نشيط جدًا اليوم.',
    advice: 'دوّني أفكارك قبل ما تضيع.',
    routine: ['كتابة أفكار', 'ممارسة هواية', 'تقليل المشتتات', 'وقت راحة'],
    supportMessage: 'طاقتك الجميلة واضحة جدًا النهارده ✨',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'content', 'loved', 'calm'},
    matchInfluences: {'family', 'relationships'},
    dayDescription: [
      'وجود العيلة مريحني نفسيًا 🥰',
      'حاسة بأمان وراحة 😌',
      'اليوم دافي ولطيف 🙂',
    ],
    insight: 'الأمان العاطفي مهم جدًا ليكي.',
    advice: 'قربي من الناس اللي بيدوك شعور بالأمان.',
    routine: ['وقت عائلي', 'أكل بتحبيه', 'قعدة هادية', 'نوم بدري'],
    supportMessage: 'القلب اللي يحب الدفا يستحقه 🤍',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'excited', 'happy', 'strong'},
    matchInfluences: {'exercise', 'achievement'},
    dayDescription: [
      'طاقتي أعلى من المعتاد 🤩',
      'الحركة حسنت مودّي جدًا 😊',
      'حاسة بقوة وثقة 💪',
    ],
    insight: 'جسمك ونفسيتك متأثرين إيجابيًا بالنشاط.',
    advice: 'استمري في أي نشاط يحسن طاقتك.',
    routine: ['حركة أو رياضة', 'أكل صحي', 'ميه كفاية', 'نوم منتظم'],
    supportMessage: 'الطاقة الحلوة اللي عندك معدية فعلًا ✨',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'happy', 'grateful', 'loved'},
    matchInfluences: {'gratitude', 'relationships', 'routine'},
    dayDescription: [
      'حاسة إن الحاجات البسيطة كفاية 😊',
      'الامتنان مخليني أهدى 🤍',
      'فيه حب وراحة حواليا 🥰',
    ],
    insight: 'أنتِ في حالة رضا نفسي لطيفة ومتوازنة.',
    advice: 'حافظي على تقدير اللحظات الصغيرة.',
    routine: ['كتابة الامتنان', 'وقت مع شخص بتحبيه', 'تقليل الضغط', 'لحظة هدوء قبل النوم'],
    supportMessage: 'الراحة اللي جواكي دي تستحق تحافظي عليها 🤍',
  ),

  // ═══════════ متوسطة 😐 ═══════════
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'neutral', 'calm', 'content'},
    matchInfluences: {'routine', 'weather'},
    dayDescription: [
      'اليوم عادي وهادي 😶',
      'مفيش حاجة مميزة لكن مرتاحة شوية 😌',
      'طاقتي متوسطة بدون ضغط كبير 🙂',
    ],
    insight: 'أنتِ في حالة هدوء واستقرار نسبي.',
    advice: 'استمتعي بالراحة البسيطة ومتضغطيش نفسك.',
    routine: ['ترتيب بسيط', 'مشروب دافي', 'وقت هدوء', 'نوم بدري'],
    supportMessage: 'مش لازم كل يوم يكون مليان حماس 🤍',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'calm', 'grateful', 'neutral'},
    matchInfluences: {'nature', 'routine'},
    dayDescription: [
      'بحاول أركز على الحاجات البسيطة 🤍',
      'اليوم هادي بدون توتر 😌',
      'فيه راحة خفيفة جوايا 😶',
    ],
    insight: 'أنتِ بتحاولي تحافظي على توازنك النفسي.',
    advice: 'خدي الأمور ببساطة أكتر.',
    routine: ['تمشية خفيفة', 'تنفس ببطء', 'تقليل الضوضاء', 'وقت بعيد عن السوشيال'],
    supportMessage: 'الهدوء النفسي الصغير ده مهم جدًا 🤍',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'content', 'loved', 'neutral'},
    matchInfluences: {'relationships', 'family'},
    dayDescription: [
      'وجود الناس اللي بحبهم مطمني 🥰',
      'يوم بسيط لكنه مريح 🙂',
      'حاسة بدفا نفسي خفيف 😶',
    ],
    insight: 'الأمان العاطفي بيريحك حتى في الأيام العادية.',
    advice: 'اقضي وقت أكتر مع الناس المريحة ليكي.',
    routine: ['قعدة عائلية', 'مكالمة لطيفة', 'أكل بتحبيه', 'هدوء قبل النوم'],
    supportMessage: 'الراحة البسيطة دي نعمة فعلًا 🥰',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'hopeful', 'calm', 'content'},
    matchInfluences: {'learning', 'weather'},
    dayDescription: [
      'حاسة إن الأمور هتبقى أحسن 🌱',
      'فيه هدوء نفسي لطيف 😌',
      'اليوم مر بشكل مريح 🙂',
    ],
    insight: 'أنتِ بتحاولي تشوفي الجانب المريح حتى في الأيام العادية.',
    advice: 'متقلقيش من البطء… التقدم الهادئ مهم.',
    routine: ['قراءة بسيطة', 'كتابة أفكار', 'وقت راحة', 'تقليل التفكير الزائد'],
    supportMessage: 'كل حاجة بتيجي في وقتها 🤍',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'neutral', 'overwhelmed', 'calm'},
    matchInfluences: {'work', 'sleep'},
    dayDescription: [
      'عندي إرهاق خفيف لكن مسيطرة 😌',
      'اليوم مر بشكل عادي 😶',
      'محتاجة راحة أكتر 🤯',
    ],
    insight: 'أنتِ مش سيئة نفسيًا لكن جسمك وعقلك محتاجين تهدئة.',
    advice: 'الراحة جزء مهم من الإنتاجية.',
    routine: ['تقليل المهام', 'ميه كفاية', 'راحة بدون ذنب', 'نوم أبكر'],
    supportMessage: 'أحيانًا أهدى أيامنا بتكون الأكثر احتياجًا للراحة 🤍',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'calm', 'hopeful', 'grateful'},
    matchInfluences: {'gratitude', 'nature'},
    dayDescription: [
      'ممتنة للحاجات الصغيرة 🤍',
      'الجو مريحني نفسيًا 🌱',
      'فيه سلام داخلي بسيط 😌',
    ],
    insight: 'أنتِ قادرة تلاقي راحة حتى في التفاصيل الصغيرة.',
    advice: 'استمري في تقدير اللحظات الهادية.',
    routine: ['كتابة امتنان', 'قعدة في مكان هادي', 'موسيقى مريحة', 'تنفس ببطء'],
    supportMessage: 'القلب الهادي يرتاح بالحاجات البسيطة 🤍',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'content', 'calm', 'hopeful'},
    matchInfluences: {'hobby', 'routine'},
    dayDescription: [
      'ممارسة حاجة بحبها حسنت يومي 🙂',
      'فيه هدوء وطاقة خفيفة 🌱',
      'يوم بسيط لكنه لطيف 😌',
    ],
    insight: 'الهوايات والروتين المريح بيأثروا على نفسيتك بشكل واضح.',
    advice: 'خلي لنفسك وقت ثابت للحاجات اللي بتحبيها.',
    routine: ['ممارسة هواية', 'تقليل الضغط', 'وقت بدون موبايل', 'مشروب بتحبيه'],
    supportMessage: 'أنتِ تستحقي أيام هادية ومريحة 🤍',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'neutral', 'loved', 'calm'},
    matchInfluences: {'relationships', 'friends'},
    dayDescription: [
      'الناس المريحة خلت يومي ألطف 🥰',
      'مفيش مشاعر قوية لكن فيه راحة 😶',
      'حاسة بهدوء نفسي 😌',
    ],
    insight: 'الاهتمام البسيط من الناس بيفرق معاكِ جدًا.',
    advice: 'متبعديش عن الأشخاص اللي بيريحوكي نفسيًا.',
    routine: ['مكالمة مع شخص قريب', 'قعدة خفيفة', 'تقليل العزلة', 'نوم منتظم'],
    supportMessage: 'وجود ناس حلوة حوالينا يهون أيام كتير 🤍',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'content', 'neutral', 'grateful'},
    matchInfluences: {'routine', 'health'},
    dayDescription: [
      'جسمي أهدى من الأيام اللي فاتت 🙂',
      'اليوم مستقر بشكل بسيط 😶',
      'ممتنة لأي لحظة راحة 🤍',
    ],
    insight: 'أنتِ محتاجة استقرار وراحة أكتر من الحماس الكبير.',
    advice: 'اسمعي لجسمك ومتهمليش راحتك.',
    routine: ['أكل خفيف', 'ميه كفاية', 'راحة وقت التعب', 'نوم منتظم'],
    supportMessage: 'الاستقرار البسيط يعتبر إنجاز أحيانًا 🤍',
  ),

  // ═══════════ ليست جيدة 😔 ═══════════
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'overwhelmed', 'anxious', 'guilty'},
    matchInfluences: {'work', 'inner_voice'},
    dayDescription: [
      'عقلي مش بيسكت وده مرهقني 😟',
      'حاسة إني مضغوطة طول الوقت 🤯',
      'بلوم نفسي على أقل حاجة 😔',
    ],
    insight: 'أنتِ تحت ضغط ذهني مستمر وبتحملي نفسك فوق طاقتها.',
    advice: 'عاملي نفسك بنفس اللطف اللي بتعاملي بيه غيرك.',
    routine: ['كتابة الأفكار', 'تقليل المهام', 'وقت راحة', 'نوم أبكر'],
    supportMessage: 'مش لازم تكوني قوية طول الوقت 🤍',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'lonely', 'sad', 'scared'},
    matchInfluences: {'relationships', 'social_media'},
    dayDescription: [
      'الوحدة تقيلة على قلبي 💔',
      'حاسة بخوف وحزن جوايا 😢',
      'المقارنة مأثرة على نفسيتي 😨',
    ],
    insight: 'أنتِ محتاجة احتواء وراحة نفسية أكتر من أي حلول.',
    advice: 'ابعدي شوية عن أي حاجة بتزود الضغط النفسي.',
    routine: ['تقليل السوشيال ميديا', 'مشاهدة شيء مريح', 'مكالمة مع شخص آمن', 'مشروب دافي'],
    supportMessage: 'وجودك مهم حتى وأنتِ تعبانة 🤍',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'angry', 'frustrated', 'exhausted'},
    matchInfluences: {'conflict', 'work'},
    dayDescription: [
      'الضغط متراكم فوقي 😠',
      'حاسة بإحباط كبير 😤',
      'حتى جسمي محتاج راحة 🥵',
    ],
    insight: 'أنتِ في حالة إنهاك نفسي وجسدي واضحة.',
    advice: 'قبل ما تحاولي تحلي كل حاجة… ارتاحي الأول.',
    routine: ['حمام دافي', 'أكل خفيف', 'راحة من النقاشات', 'نوم كفاية'],
    supportMessage: 'أنتِ مش ضعيفة… أنتِ فقط مرهقة 🤍',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'overwhelmed', 'calm', 'sad'},
    matchInfluences: {'health', 'sleep'},
    dayDescription: [
      'جسمي مستنزف نفسيًا وجسديًا 🤯',
      'حتى الحاجات البسيطة محتاجة مجهود 😔',
      'التعب مأثر على مودّي 😢',
    ],
    insight: 'التعب الجسدي مأثر بشكل واضح على نفسيتك.',
    advice: 'جسمك محتاج راحة مش ضغط زيادة.',
    routine: ['سوائل دافية', 'أكل مغذي', 'تقليل المهام', 'راحة كفاية'],
    supportMessage: 'كوني لطيفة مع نفسك النهارده 🤍',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'anxious', 'hopeless', 'guilty'},
    matchInfluences: {'inner_voice', 'relationships'},
    dayDescription: [
      'صوتي الداخلي قاسي عليا 😔',
      'حاسة إني مكسورة نفسيًا 😞',
      'القلق واخد مساحة كبيرة 😟',
    ],
    insight: 'أنتِ محتاجة تهوني على نفسك بدل ما تضغطيها.',
    advice: 'مش كل فكرة في دماغك حقيقة.',
    routine: ['كتابة المشاعر', 'تنفس ببطء', 'تقليل التفكير قبل النوم', 'سماع شيء مريح'],
    supportMessage: 'حتى أصعب المشاعر بتمر 🤍',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'lonely', 'overwhelmed', 'calm'},
    matchInfluences: {'relationships', 'routine'},
    dayDescription: [
      'حاسة بوحدة رغم هدوء اليوم 💔',
      'طاقتي أقل من المعتاد 🤯',
      'بحاول أعدي اليوم بهدوء 😔',
    ],
    insight: 'أنتِ محتاجة دعم نفسي واحتواء بسيط.',
    advice: 'متنعزليش وقت التعب.',
    routine: ['مكالمة مع حد قريب', 'أكل بتحبيه', 'وقت بعيد عن الضغط', 'نوم بدري'],
    supportMessage: 'أنتِ تستحقي الاحتواء والراحة 🤍',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'frustrated', 'anxious', 'overwhelmed'},
    matchInfluences: {'work', 'future'},
    dayDescription: [
      'التفكير في المستقبل مقلقني 😟',
      'حاسة إن الضغط أكبر مني 😤',
      'عقلي مرهق جدًا 🤯',
    ],
    insight: 'التفكير الزائد مستنزف طاقتك النفسية.',
    advice: 'ركزي على خطوة واحدة فقط دلوقتي.',
    routine: ['تقسيم المهام', 'تقليل الضغط', 'كتابة الأولويات', 'راحة بين المهام'],
    supportMessage: 'مش لازم تحلي كل حاجة مرة واحدة 🤍',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'sad', 'calm', 'scared'},
    matchInfluences: {'news', 'social_media'},
    dayDescription: [
      'الأخبار مأثرة على نفسيتي 😢',
      'حاسة بخوف داخلي 😨',
      'مودّي أهدى لكنه حزين 😔',
    ],
    insight: 'أنتِ متأثرة بالطاقة السلبية اللي حواليك.',
    advice: 'خدي بريك من أي محتوى متعب نفسيًا.',
    routine: ['تقليل الأخبار', 'موسيقى مريحة', 'وقت هدوء', 'شرب ميه كفاية'],
    supportMessage: 'قلبك محتاج هدوء أكتر من أي حاجة 🤍',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'exhausted', 'frustrated', 'sad'},
    matchInfluences: {'period', 'body'},
    dayDescription: [
      'هرموناتي مأثرة على مودّي جدًا 🌸',
      'نفسيتي أضعف من المعتاد 😢',
      'جسمي وعقلي محتاجين راحة 🥵',
    ],
    insight: 'أنتِ متأثرة جسديًا وهرمونيًا وده طبيعي جدًا.',
    advice: 'خففي توقعاتك من نفسك في الأيام دي.',
    routine: ['مشروب دافي', 'شوكولاتة أو أكل مريح', 'بطانية وفيلم هادي', 'نوم كفاية'],
    supportMessage: 'مشاعرك الحالية حقيقية ومفهومة جدًا 🤍',
  ),

  // ═══════════ سيئة 😢 ═══════════
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'sad', 'lonely', 'scared'},
    matchInfluences: {'relationships', 'social_media'},
    dayDescription: [
      'حاسة بثقل وحزن طول اليوم 😭',
      'الوحدة مأثرة على قلبي جدًا 💔',
      'فيه خوف وقلق مش قادرين يهدوا 😨',
    ],
    insight: 'أنتِ مستنزفة نفسيًا ومحتاجة أمان واحتواء أكتر من أي نصيحة.',
    advice: 'ابعدي شوية عن أي حاجة بتزود المقارنة أو التوتر.',
    routine: ['إغلاق السوشيال ميديا لفترة', 'مشروب دافي', 'حضن أو مكالمة مريحة', 'نوم بدري'],
    supportMessage: 'أعرف إنك تعبانة… لكنك تستحقي الرحمة مش القسوة 🤍',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'angry', 'frustrated', 'exhausted'},
    matchInfluences: {'conflict', 'work'},
    dayDescription: [
      'كل حاجة فوق طاقتي 😠',
      'الإحباط مسيطر عليا 😤',
      'حتى جسمي محتاج راحة 🥵',
    ],
    insight: 'أنتِ في مرحلة ضغط نفسي وجسدي كبيرة.',
    advice: 'مش لازم تصلحي كل حاجة في يوم واحد.',
    routine: ['حمام دافي', 'وجبة خفيفة', 'راحة من النقاشات', 'نوم كفاية'],
    supportMessage: 'أنتِ مش فاشلة… أنتِ فقط مرهقة جدًا 🤍',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'hopeless', 'guilty', 'anxious'},
    matchInfluences: {'inner_voice', 'relationships'},
    dayDescription: [
      'صوتي الداخلي قاسي عليا 😔',
      'حاسة بخوف وتوتر طول الوقت 😟',
      'قلبي متعب ومش قادرة أهدى 😞',
    ],
    insight: 'أنتِ بتمري بحالة حساسة نفسيًا ومحتاجة تهوني على نفسك.',
    advice: 'مش كل فكرة سلبية حقيقية.',
    routine: ['كتابة مشاعرك', 'تقليل التفكير قبل النوم', 'تنفس ببطء', 'سماع شيء مريح'],
    supportMessage: 'حتى أصعب المشاعر بتمر… ومش لازم تعديها لوحدك 🤍',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'exhausted', 'sad', 'overwhelmed'},
    matchInfluences: {'health', 'body'},
    dayDescription: [
      'جسمي مستنزف جدًا 🥵',
      'التعب مأثر على نفسيتي 😢',
      'حتى أبسط الحاجات محتاجة مجهود 🤯',
    ],
    insight: 'الإرهاق الجسدي مأثر على مشاعرك بشكل واضح.',
    advice: 'جسمك محتاج احتواء وراحة مش ضغط.',
    routine: ['سوائل دافية', 'أكل مغذي', 'تقليل المهام', 'راحة بدون ذنب'],
    supportMessage: 'كوني حنونة على نفسك النهارده 🤍',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'frustrated', 'scared', 'sad'},
    matchInfluences: {'future', 'work'},
    dayDescription: [
      'التفكير في المستقبل مخوفني 😨',
      'حاسة إن الضغط أكبر مني 😤',
      'الحزن واخد مساحة كبيرة 😢',
    ],
    insight: 'أنتِ تحت ضغط التفكير الزائد والخوف من المجهول.',
    advice: 'ركزي على يومك الحالي بدل كل المستقبل مرة واحدة.',
    routine: ['تقسيم المهام', 'كتابة الأولويات', 'وقت راحة', 'تقليل التفكير ليلًا'],
    supportMessage: 'مش لازم تعرفي كل الإجابات دلوقتي 🤍',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'lonely', 'hopeless', 'overwhelmed'},
    matchInfluences: {'relationships', 'isolation'},
    dayDescription: [
      'حاسة إني لوحدي جدًا 💔',
      'قلبي مكسور ومتعب 😞',
      'طاقتي النفسية منتهية 🤯',
    ],
    insight: 'أنتِ محتاجة احتواء حقيقي وشعور بالأمان.',
    advice: 'حاولي متنعزليش تمامًا وقت التعب.',
    routine: ['مكالمة مع شخص قريب', 'مشاهدة شيء مريح', 'أكل بتحبيه', 'نوم بدري'],
    supportMessage: 'وجودك مهم حتى لو أنتِ مش شايفة ده دلوقتي 🤍',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'angry', 'exhausted', 'anxious'},
    matchInfluences: {'conflict', 'inner_voice'},
    dayDescription: [
      'أعصابي مستنزفة جدًا 😠',
      'القلق والتفكير مش مخليني أرتاح 😟',
      'جسمي وعقلي محتاجين هدوء 🥵',
    ],
    insight: 'أنتِ في حالة توتر واستنزاف عصبي.',
    advice: 'ابعدي عن أي نقاش أو ضغط إضافي اليوم.',
    routine: ['تنفس ببطء', 'تقليل الضوضاء', 'حمام دافي', 'راحة بدون موبايل'],
    supportMessage: 'أنتِ محتاجة هدوء أكتر من الحلول دلوقتي 🤍',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'sad', 'overwhelmed', 'scared'},
    matchInfluences: {'news', 'social_media'},
    dayDescription: [
      'الأخبار مأثرة على مودّي 😢',
      'حاسة بخوف وتوتر داخلي 😨',
      'عقلي مرهق من التفكير 🤯',
    ],
    insight: 'الطاقة السلبية اللي حواليك مأثرة على نفسيتك.',
    advice: 'اعملي بريك من الأخبار والسوشيال شوية.',
    routine: ['موسيقى هادية', 'وقت بعيد عن الشاشة', 'شرب ميه', 'نوم كفاية'],
    supportMessage: 'قلبك محتاج راحة وهدوء 🤍',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'exhausted', 'frustrated', 'sad'},
    matchInfluences: {'period', 'body'},
    dayDescription: [
      'هرموناتي مأثرة على نفسيتي جدًا 🌸',
      'نفسيتي أضعف من المعتاد 😢',
      'جسمي محتاج راحة حقيقية 🥵',
    ],
    insight: 'أنتِ متأثرة جسديًا وهرمونيًا وده طبيعي جدًا.',
    advice: 'خففي توقعاتك من نفسك في الأيام دي.',
    routine: ['مشروب دافي', 'بطانية وفيلم مريح', 'أكل بتحبيه', 'نوم كفاية'],
    supportMessage: 'مشاعرك الحالية حقيقية ومفهومة جدًا 🤍',
  ),
];
