/// Catalog of reflection scenarios — 45 scenarios (9 per mood).
///
/// Ported verbatim from the Android Kotlin source
/// (`com.gpstracker.routiny.reflection.ReflectionScenarios`).
/// All Arabic text is preserved exactly.
///
/// ignore_for_file: unused_import
import 'reflection_models.dart';

class ReflectionScenario {
  final String moodId;
  final Set<String> matchFeelings; // feeling ids
  final Set<String> matchInfluences; // influence ids
  final List<String> dayDescription; // 3 lines
  final String insight;
  final String advice;
  final List<String> routine; // 4 items
  final String supportMessage;
  // Fusha variants — empty string means "fall back to masri"
  final List<String> dayDescriptionFusha;
  final String insightFusha;
  final String adviceFusha;
  final List<String> routineFusha;
  final String supportMessageFusha;

  const ReflectionScenario({
    required this.moodId,
    required this.matchFeelings,
    required this.matchInfluences,
    required this.dayDescription,
    required this.insight,
    required this.advice,
    required this.routine,
    required this.supportMessage,
    this.dayDescriptionFusha = const [],
    this.insightFusha = '',
    this.adviceFusha = '',
    this.routineFusha = const [],
    this.supportMessageFusha = '',
  });
}

const reflectionScenarios = <ReflectionScenario>[
  // ═══════════ رائعة 😄 ═══════════
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'happy', 'grateful', 'calm'},
    matchInfluences: {'family', 'routine'},
    dayDescription: [
      'اليوم كان مريح وقلبي هادي 🤍',
      'وجود الناس اللي بحبهم فرق معايا 😊',
      'حاسة براحة نفسية جميلة 😌',
    ],
    insight: 'أنتِ في حالة سلام وامتنان داخلي.',
    advice: 'استمتعي باللحظات البسيطة ومتستعجليش الأيام.',
    routine: ['كتابة امتنان', 'وقت هدوء', 'مشروب دافي', 'نوم منتظم'],
    supportMessage: 'الراحة اللي جواكي نعمة تستحقيها 🤍',
    dayDescriptionFusha: ['كان يومي مريحا وقلبي هادئ', 'وجود الأشخاص الذين أحبهم أحدث فارقا معي', 'أشعر براحة نفسية جميلة'],
    insightFusha: 'أنت في حالة سلام وامتنان داخلي.',
    adviceFusha: 'استمتعي باللحظات البسيطة ولا تتعجلي الأيام.',
    routineFusha: ['كتابة الامتنان', 'وقت الهدوء', 'مشروب دافئ', 'نوم منتظم'],
    supportMessageFusha: 'الراحة التي بداخلك نعمة تستحقينها',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'proud', 'excited', 'strong'},
    matchInfluences: {'achievement', 'work'},
    dayDescription: [
      'إنجاز صغير خلاني فخورة ✨',
      'عندي طاقة أكمل أكتر 🤩',
      'حاسة إني قادرة على حاجات كتير 💪',
    ],
    insight: 'ثقتك بنفسك بدأت تزيد بسبب مجهودك.',
    advice: 'احتفلي بأي تقدم حتى لو بسيط.',
    routine: ['To-do صغيرة', 'استراحة بين المهام', 'مكافأة بسيطة', 'تقليل التشتت'],
    supportMessage: 'أنتِ أقوى مما تتخيلي فعلًا ✨',
    dayDescriptionFusha: ['إنجاز صغير جعلني فخورة', 'لدي طاقة لأكمل أكثر', 'أشعر بأنني قادرة على أشياء كثيرة'],
    insightFusha: 'ثقتك بنفسك بدأت تزيد بسبب مجهودك.',
    adviceFusha: 'احتفلي بأي تقدم حتى لو كان بسيطا.',
    routineFusha: ['قائمة مهام صغيرة', 'استراحة بين المهام', 'مكافأة بسيطة', 'تقليل التشتت'],
    supportMessageFusha: 'أنت أقوى مما تتخيلين فعلا',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'loved', 'content', 'happy'},
    matchInfluences: {'relationships', 'friends'},
    dayDescription: [
      'وجود الناس الصح مريحني 🥰',
      'قلبي أخف النهارده 🙂',
      'حاسة بحب واهتمام 😊',
    ],
    insight: 'الأمان العاطفي بيأثر على مودك جدًا.',
    advice: 'قربي من الناس اللي يطمنوك نفسيًا.',
    routine: ['قعدة لطيفة', 'مكالمة مع شخص قريب', 'موسيقى هادية', 'وقت بعيد عن الضغط'],
    supportMessage: 'وجودك مريح وجميل للي حواليك 🥰',
    dayDescriptionFusha: ['وجود الأشخاص المناسبين أراحني', 'قلبي أخف اليوم', 'أشعر بالحب والاهتمام'],
    insightFusha: 'الأمان العاطفي يؤثر على مزاجك تأثيرا كبيرا.',
    adviceFusha: 'اقتربي من الأشخاص الذين يطمئنونك نفسيا.',
    routineFusha: ['جلسة لطيفة', 'مكالمة مع شخص قريب', 'موسيقى هادئة', 'وقت بعيد عن الضغط'],
    supportMessageFusha: 'وجودك مريح وجميل لمن حولك',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'inspired', 'happy', 'hopeful'},
    matchInfluences: {'hobby', 'learning'},
    dayDescription: [
      'أفكاري ماشية بشكل جميل 💡',
      'عندي رغبة أبدأ حاجات جديدة 🌱',
      'حاسة بطاقة حلوة 😊',
    ],
    insight: 'الجانب الإبداعي عندك نشيط جدًا اليوم.',
    advice: 'سجلي أفكارك قبل ما تضيع.',
    routine: ['كتابة أفكار', 'ممارسة هواية', 'وقت هدوء', 'تقليل المشتتات'],
    supportMessage: 'طاقتك الحلوة واضحة جدًا ✨',
    dayDescriptionFusha: ['أفكاري تسير بشكل جميل', 'لدي رغبة في البدء بأشياء جديدة', 'أشعر بطاقة جميلة'],
    insightFusha: 'الجانب الإبداعي لديك نشيط جدا اليوم.',
    adviceFusha: 'سجلي أفكارك قبل أن تضيع.',
    routineFusha: ['كتابة الأفكار', 'ممارسة هواية', 'وقت هدوء', 'تقليل المشتتات'],
    supportMessageFusha: 'طاقتك الجميلة واضحة جدا',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'excited', 'strong', 'proud'},
    matchInfluences: {'exercise', 'achievement'},
    dayDescription: [
      'الحركة حسنت مودّي جدًا 🤩',
      'حاسة بطاقة وقوة 💪',
      'فخورة بنفسي النهارده ✨',
    ],
    insight: 'النشاط والحركة انعكسوا بشكل إيجابي على نفسيتك.',
    advice: 'استمري في أي نشاط يحسسك بالحيوية.',
    routine: ['رياضة خفيفة', 'ميه كفاية', 'أكل صحي', 'نوم بدري'],
    supportMessage: 'أنتِ بتخلقي طاقتك الحلوة بنفسك ✨',
    dayDescriptionFusha: ['الحركة حسنت مزاجي كثيرا', 'أشعر بطاقة وقوة', 'فخورة بنفسي اليوم'],
    insightFusha: 'النشاط والحركة انعكسا بشكل إيجابي على نفسيتك.',
    adviceFusha: 'استمري في أي نشاط يمنحك الحيوية.',
    routineFusha: ['رياضة خفيفة', 'شرب ماء كافٍ', 'أكل صحي', 'نوم مبكر'],
    supportMessageFusha: 'أنت تصنعين طاقتك الجميلة بنفسك',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'grateful', 'calm', 'loved'},
    matchInfluences: {'family', 'gratitude'},
    dayDescription: [
      'حاسة بدفا جميل حواليا 🥰',
      'قلبي هادي ومبسوط 😌',
      'ممتنة للحاجات البسيطة 🤍',
    ],
    insight: 'أنتِ في حالة رضا داخلي لطيفة جدًا.',
    advice: 'حافظي على اللحظات اللي بتحسسك بالأمان.',
    routine: ['وقت عائلي', 'أكل بتحبيه', 'هدوء قبل النوم', 'كتابة شعورك'],
    supportMessage: 'القلب الهادي ده يستحق الراحة دائمًا 🤍',
    dayDescriptionFusha: ['أشعر بدفء جميل من حولي', 'قلبي هادئ وسعيد', 'ممتنة للأشياء البسيطة'],
    insightFusha: 'أنت في حالة رضا داخلي لطيفة جدا.',
    adviceFusha: 'حافظي على اللحظات التي تمنحك الأمان.',
    routineFusha: ['وقت عائلي', 'طعام تحبينه', 'هدوء قبل النوم', 'كتابة مشاعرك'],
    supportMessageFusha: 'القلب الهادئ يستحق الراحة دائما',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'happy', 'hopeful', 'content'},
    matchInfluences: {'nature', 'weather'},
    dayDescription: [
      'الجو محسسني براحة 🌱',
      'يوم بسيط لكنه لطيف 😊',
      'حاسة بهدوء نفسي جميل 🙂',
    ],
    insight: 'أنتِ متصالحة مع نفسك أكتر اليوم.',
    advice: 'استغلي الأيام الهادية في شحن طاقتك.',
    routine: ['تمشية بسيطة', 'مشروب دافي', 'موسيقى هادية', 'نوم منتظم'],
    supportMessage: 'الهدوء اللي جواكي جميل فعلًا 🤍',
    dayDescriptionFusha: ['الطقس منحني راحة', 'يوم بسيط لكنه لطيف', 'أشعر بهدوء نفسي جميل'],
    insightFusha: 'أنت متصالحة مع نفسك أكثر اليوم.',
    adviceFusha: 'استغلي الأيام الهادئة في شحن طاقتك.',
    routineFusha: ['تمشية بسيطة', 'مشروب دافئ', 'موسيقى هادئة', 'نوم منتظم'],
    supportMessageFusha: 'الهدوء الذي بداخلك جميل فعلا',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'proud', 'loved', 'inspired'},
    matchInfluences: {'relationships', 'achievement'},
    dayDescription: [
      'حاسة إني متقدرة من اللي حواليا 🥰',
      'فخورة بنفسي ومجهودي ✨',
      'عندي طاقة إيجابية جميلة 💡',
    ],
    insight: 'الاهتمام والتقدير بيأثروا فيكي بشكل كبير.',
    advice: 'كملي في الطريق اللي محسسك بقيمتك.',
    routine: ['مشاركة إنجازاتك', 'وقت مع ناس مريحة', 'كتابة أفكارك', 'تقليل الضغط'],
    supportMessage: 'أنتِ تستحقي كل شعور حلو بتحسيه 🤍',
    dayDescriptionFusha: ['أشعر بأنني موضع تقدير ممن حولي', 'فخورة بنفسي وبجهدي', 'لدي طاقة إيجابية جميلة'],
    insightFusha: 'الاهتمام والتقدير يؤثران فيك بشكل كبير.',
    adviceFusha: 'واصلي السير في الطريق الذي يجعلك تشعرين بقيمتك.',
    routineFusha: ['مشاركة إنجازاتك', 'وقت مع أشخاص مريحين', 'كتابة أفكارك', 'تقليل الضغط'],
    supportMessageFusha: 'أنت تستحقين كل شعور جميل تحسينه',
  ),
  ReflectionScenario(
    moodId: 'wonderful',
    matchFeelings: {'calm', 'happy', 'strong'},
    matchInfluences: {'routine', 'achievement'},
    dayDescription: [
      'يوم منظم ومريح 😌',
      'الإنجاز البسيط فرق معايا 😊',
      'حاسة بثقة وراحة 💪',
    ],
    insight: 'الاستقرار والإنجاز بيخلوا نفسيتك أفضل.',
    advice: 'كملي خطوة خطوة بدون ضغط كبير.',
    routine: ['تنظيم يومك', 'تحديد هدف صغير', 'وقت راحة', 'نوم كفاية'],
    supportMessage: 'أنتِ ماشية بشكل رائع فعلًا ✨',
    dayDescriptionFusha: ['يوم منظم ومريح', 'الإنجاز البسيط أحدث فارقا معي', 'أشعر بثقة وراحة'],
    insightFusha: 'الاستقرار والإنجاز يجعلان نفسيتك أفضل.',
    adviceFusha: 'واصلي خطوة بخطوة دون ضغط كبير.',
    routineFusha: ['تنظيم يومك', 'تحديد هدف صغير', 'وقت راحة', 'نوم كافٍ'],
    supportMessageFusha: 'أنت تسيرين بشكل رائع فعلا',
  ),

  // ═══════════ جيدة 🙂 ═══════════
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'calm', 'grateful', 'content'},
    matchInfluences: {'routine', 'weather'},
    dayDescription: [
      'اليوم هادي ومريح نفسيًا 😌',
      'فيه سلام داخلي بسيط 🤍',
      'الروتين المستقر مطمني 🙂',
    ],
    insight: 'أنتِ محتاجة استقرار وراحة أكتر من الإثارة.',
    advice: 'كملي على العادات الصغيرة اللي مريحاكي.',
    routine: ['مشروب دافي', 'ترتيب بسيط', 'قراءة خفيفة', 'نوم منتظم'],
    supportMessage: 'الهدوء النفسي نعمة كبيرة فعلًا 🤍',
    dayDescriptionFusha: ['كان يومي هادئا ومريحا نفسيا', 'ثمة سلام داخلي بسيط', 'الروتين المستقر يطمئنني'],
    insightFusha: 'أنت بحاجة إلى الاستقرار والراحة أكثر من الإثارة.',
    adviceFusha: 'واصلي العادات الصغيرة التي تريحك.',
    routineFusha: ['مشروب دافئ', 'ترتيب بسيط', 'قراءة خفيفة', 'نوم منتظم'],
    supportMessageFusha: 'الهدوء النفسي نعمة كبيرة فعلا',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'happy', 'hopeful', 'inspired'},
    matchInfluences: {'learning', 'achievement'},
    dayDescription: [
      'عندي رغبة أطور نفسي 🌱',
      'الإنجاز الصغير فرق معايا 😊',
      'حاسة بإلهام وطاقة حلوة 💡',
    ],
    insight: 'فيه حماس داخلي للنمو والتغيير الإيجابي.',
    advice: 'استثمري طاقتك في خطوة حقيقية صغيرة.',
    routine: ['To-do بسيطة', 'ساعة تعلم', 'تقليل التشتت', 'مكافأة بسيطة'],
    supportMessage: 'كل خطوة صغيرة بتقربك لنسختك الأفضل ✨',
    dayDescriptionFusha: ['لدي رغبة في تطوير نفسي', 'الإنجاز الصغير أحدث فارقا معي', 'أشعر بإلهام وطاقة جميلة'],
    insightFusha: 'ثمة حماس داخلي للنمو والتغيير الإيجابي.',
    adviceFusha: 'استثمري طاقتك في خطوة حقيقية صغيرة.',
    routineFusha: ['قائمة مهام بسيطة', 'ساعة تعلم', 'تقليل التشتت', 'مكافأة بسيطة'],
    supportMessageFusha: 'كل خطوة صغيرة تقربك من نسختك الأفضل',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'loved', 'content', 'happy'},
    matchInfluences: {'relationships', 'friends'},
    dayDescription: [
      'وجود الناس الصح مطمني 🥰',
      'قلبي مرتاح أكتر النهارده 🙂',
      'حاسة باحتواء جميل 😊',
    ],
    insight: 'أنتِ تتأثري جدًا بالحب والاهتمام الحقيقي.',
    advice: 'اقضي وقت أكتر مع الأشخاص اللي يريحوك.',
    routine: ['مكالمة لطيفة', 'قعدة مع حد قريب', 'موسيقى هادية', 'وقت بعيد عن السوشيال'],
    supportMessage: 'وجودك لطيف ومريح للي حواليك 🥰',
    dayDescriptionFusha: ['وجود الأشخاص المناسبين يطمئنني', 'قلبي أكثر ارتياحا اليوم', 'أشعر باحتواء جميل'],
    insightFusha: 'أنت تتأثرين كثيرا بالحب والاهتمام الحقيقي.',
    adviceFusha: 'اقضي وقتا أكثر مع الأشخاص الذين يريحونك.',
    routineFusha: ['مكالمة لطيفة', 'جلسة مع شخص قريب', 'موسيقى هادئة', 'وقت بعيد عن وسائل التواصل'],
    supportMessageFusha: 'وجودك لطيف ومريح لمن حولك',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'proud', 'excited', 'strong'},
    matchInfluences: {'achievement', 'work'},
    dayDescription: [
      'حاسة إني أنجزت حاجة مهمة ✨',
      'عندي حماس أكمل أكتر 🤩',
      'فخورة بالمجهود اللي عملته 💪',
    ],
    insight: 'ثقتك بنفسك بدأت تزيد بسبب تعبك الحقيقي.',
    advice: 'احتفلي بأي إنجاز حتى لو بسيط.',
    routine: ['تحديد هدف صغير', 'تنظيم الوقت', 'راحة بين المهام', 'مكافأة لنفسك'],
    supportMessage: 'أنتِ أقوى مما تتخيلي فعلًا ✨',
    dayDescriptionFusha: ['أشعر بأنني أنجزت شيئا مهما', 'لدي حماس لأكمل أكثر', 'فخورة بالجهد الذي بذلته'],
    insightFusha: 'ثقتك بنفسك بدأت تزيد بسبب تعبك الحقيقي.',
    adviceFusha: 'احتفلي بأي إنجاز حتى لو كان بسيطا.',
    routineFusha: ['تحديد هدف صغير', 'تنظيم الوقت', 'راحة بين المهام', 'مكافأة لنفسك'],
    supportMessageFusha: 'أنت أقوى مما تتخيلين فعلا',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'calm', 'neutral', 'grateful'},
    matchInfluences: {'nature', 'weather'},
    dayDescription: [
      'اليوم بسيط لكنه مريح 😌',
      'بحاول أعيش بهدوء أكتر 🤍',
      'مفيش ضغط كبير النهارده 😶',
    ],
    insight: 'أنتِ بتحاولي تحافظي على توازنك النفسي.',
    advice: 'الراحة مش كسل… دي احتياج.',
    routine: ['تمشية بسيطة', 'تنفس ببطء', 'وقت هدوء', 'تقليل الضوضاء'],
    supportMessage: 'أنتِ تستحقي السلام النفسي 🤍',
    dayDescriptionFusha: ['كان يومي بسيطا لكنه مريح', 'أحاول أن أعيش بهدوء أكثر', 'لا ضغط كبير اليوم'],
    insightFusha: 'أنت تحاولين المحافظة على توازنك النفسي.',
    adviceFusha: 'الراحة ليست كسلا... إنها احتياج.',
    routineFusha: ['تمشية بسيطة', 'تنفس ببطء', 'وقت هدوء', 'تقليل الضوضاء'],
    supportMessageFusha: 'أنت تستحقين السلام النفسي',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'inspired', 'hopeful', 'proud'},
    matchInfluences: {'hobby', 'learning'},
    dayDescription: [
      'أفكاري متدفقة بشكل جميل 💡',
      'عندي أمل وحماس للفترة الجاية 🌱',
      'حاسة بفخر تجاه نفسي ✨',
    ],
    insight: 'الجانب الإبداعي عندك نشيط جدًا اليوم.',
    advice: 'دوّني أفكارك قبل ما تضيع.',
    routine: ['كتابة أفكار', 'ممارسة هواية', 'تقليل المشتتات', 'وقت راحة'],
    supportMessage: 'طاقتك الجميلة واضحة جدًا النهارده ✨',
    dayDescriptionFusha: ['أفكاري متدفقة بشكل جميل', 'لدي أمل وحماس للمرحلة القادمة', 'أشعر بفخر تجاه نفسي'],
    insightFusha: 'الجانب الإبداعي لديك نشيط جدا اليوم.',
    adviceFusha: 'دوني أفكارك قبل أن تضيع.',
    routineFusha: ['كتابة الأفكار', 'ممارسة هواية', 'تقليل المشتتات', 'وقت راحة'],
    supportMessageFusha: 'طاقتك الجميلة واضحة جدا اليوم',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'content', 'loved', 'calm'},
    matchInfluences: {'family', 'relationships'},
    dayDescription: [
      'وجود العيلة مريحني نفسيًا 🥰',
      'حاسة بأمان وراحة 😌',
      'اليوم دافي ولطيف 🙂',
    ],
    insight: 'الأمان العاطفي مهم جدًا ليكي.',
    advice: 'قربي من الناس اللي بيدوك شعور بالأمان.',
    routine: ['وقت عائلي', 'أكل بتحبيه', 'قعدة هادية', 'نوم بدري'],
    supportMessage: 'القلب اللي يحب الدفا يستحقه 🤍',
    dayDescriptionFusha: ['وجود العائلة أراحني نفسيا', 'أشعر بالأمان والراحة', 'كان يومي دافئا ولطيفا'],
    insightFusha: 'الأمان العاطفي مهم جدا لك.',
    adviceFusha: 'اقتربي من الأشخاص الذين يمنحونك شعور الأمان.',
    routineFusha: ['وقت عائلي', 'طعام تحبينه', 'جلسة هادئة', 'نوم مبكر'],
    supportMessageFusha: 'القلب الذي يحب الدفء يستحقه',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'excited', 'happy', 'strong'},
    matchInfluences: {'exercise', 'achievement'},
    dayDescription: [
      'طاقتي أعلى من المعتاد 🤩',
      'الحركة حسنت مودّي جدًا 😊',
      'حاسة بقوة وثقة 💪',
    ],
    insight: 'جسمك ونفسيتك متأثرين إيجابيًا بالنشاط.',
    advice: 'استمري في أي نشاط يحسن طاقتك.',
    routine: ['حركة أو رياضة', 'أكل صحي', 'ميه كفاية', 'نوم منتظم'],
    supportMessage: 'الطاقة الحلوة اللي عندك معدية فعلًا ✨',
    dayDescriptionFusha: ['طاقتي أعلى من المعتاد', 'الحركة حسنت مزاجي كثيرا', 'أشعر بقوة وثقة'],
    insightFusha: 'جسدك ونفسيتك يتأثران إيجابيا بالنشاط.',
    adviceFusha: 'استمري في أي نشاط يحسن طاقتك.',
    routineFusha: ['حركة أو رياضة', 'أكل صحي', 'شرب ماء كافٍ', 'نوم منتظم'],
    supportMessageFusha: 'الطاقة الجميلة التي لديك معدية فعلا',
  ),
  ReflectionScenario(
    moodId: 'good',
    matchFeelings: {'happy', 'grateful', 'loved'},
    matchInfluences: {'gratitude', 'relationships', 'routine'},
    dayDescription: [
      'حاسة إن الحاجات البسيطة كفاية 😊',
      'الامتنان مخليني أهدى 🤍',
      'فيه حب وراحة حواليا 🥰',
    ],
    insight: 'أنتِ في حالة رضا نفسي لطيفة ومتوازنة.',
    advice: 'حافظي على تقدير اللحظات الصغيرة.',
    routine: ['كتابة الامتنان', 'وقت مع شخص بتحبيه', 'تقليل الضغط', 'لحظة هدوء قبل النوم'],
    supportMessage: 'الراحة اللي جواكي دي تستحق تحافظي عليها 🤍',
    dayDescriptionFusha: ['أشعر بأن الأشياء البسيطة تكفي', 'الامتنان يجعلني أكثر هدوءا', 'ثمة حب وراحة من حولي'],
    insightFusha: 'أنت في حالة رضا نفسي لطيفة ومتوازنة.',
    adviceFusha: 'حافظي على تقدير اللحظات الصغيرة.',
    routineFusha: ['كتابة الامتنان', 'وقت مع شخص تحبينه', 'تقليل الضغط', 'لحظة هدوء قبل النوم'],
    supportMessageFusha: 'الراحة التي بداخلك تستحق أن تحافظي عليها',
  ),

  // ═══════════ متوسطة 😐 ═══════════
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'neutral', 'calm', 'content'},
    matchInfluences: {'routine', 'weather'},
    dayDescription: [
      'اليوم عادي وهادي 😶',
      'مفيش حاجة مميزة لكن مرتاحة شوية 😌',
      'طاقتي متوسطة بدون ضغط كبير 🙂',
    ],
    insight: 'أنتِ في حالة هدوء واستقرار نسبي.',
    advice: 'استمتعي بالراحة البسيطة ومتضغطيش نفسك.',
    routine: ['ترتيب بسيط', 'مشروب دافي', 'وقت هدوء', 'نوم بدري'],
    supportMessage: 'مش لازم كل يوم يكون مليان حماس 🤍',
    dayDescriptionFusha: ['كان يومي عاديا وهادئا', 'لا شيء مميز لكنني مرتاحة قليلا', 'طاقتي متوسطة دون ضغط كبير'],
    insightFusha: 'أنت في حالة هدوء واستقرار نسبي.',
    adviceFusha: 'استمتعي بالراحة البسيطة ولا تضغطي على نفسك.',
    routineFusha: ['ترتيب بسيط', 'مشروب دافئ', 'وقت هدوء', 'نوم مبكر'],
    supportMessageFusha: 'ليس من الضروري أن يكون كل يوم مليئا بالحماس',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'calm', 'grateful', 'neutral'},
    matchInfluences: {'nature', 'routine'},
    dayDescription: [
      'بحاول أركز على الحاجات البسيطة 🤍',
      'اليوم هادي بدون توتر 😌',
      'فيه راحة خفيفة جوايا 😶',
    ],
    insight: 'أنتِ بتحاولي تحافظي على توازنك النفسي.',
    advice: 'خدي الأمور ببساطة أكتر.',
    routine: ['تمشية خفيفة', 'تنفس ببطء', 'تقليل الضوضاء', 'وقت بعيد عن السوشيال'],
    supportMessage: 'الهدوء النفسي الصغير ده مهم جدًا 🤍',
    dayDescriptionFusha: ['أحاول التركيز على الأشياء البسيطة', 'كان يومي هادئا دون توتر', 'ثمة راحة خفيفة بداخلي'],
    insightFusha: 'أنت تحاولين المحافظة على توازنك النفسي.',
    adviceFusha: 'تعاملي مع الأمور بمزيد من البساطة.',
    routineFusha: ['تمشية خفيفة', 'تنفس ببطء', 'تقليل الضوضاء', 'وقت بعيد عن وسائل التواصل'],
    supportMessageFusha: 'هذا الهدوء النفسي البسيط مهم جدا',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'content', 'loved', 'neutral'},
    matchInfluences: {'relationships', 'family'},
    dayDescription: [
      'وجود الناس اللي بحبهم مطمني 🥰',
      'يوم بسيط لكنه مريح 🙂',
      'حاسة بدفا نفسي خفيف 😶',
    ],
    insight: 'الأمان العاطفي بيريحك حتى في الأيام العادية.',
    advice: 'اقضي وقت أكتر مع الناس المريحة ليكي.',
    routine: ['قعدة عائلية', 'مكالمة لطيفة', 'أكل بتحبيه', 'هدوء قبل النوم'],
    supportMessage: 'الراحة البسيطة دي نعمة فعلًا 🥰',
    dayDescriptionFusha: ['وجود الأشخاص الذين أحبهم يطمئنني', 'يوم بسيط لكنه مريح', 'أشعر بدفء نفسي خفيف'],
    insightFusha: 'الأمان العاطفي يريحك حتى في الأيام العادية.',
    adviceFusha: 'اقضي وقتا أكثر مع الأشخاص المريحين لك.',
    routineFusha: ['جلسة عائلية', 'مكالمة لطيفة', 'طعام تحبينه', 'هدوء قبل النوم'],
    supportMessageFusha: 'هذه الراحة البسيطة نعمة فعلا',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'hopeful', 'calm', 'content'},
    matchInfluences: {'learning', 'weather'},
    dayDescription: [
      'حاسة إن الأمور هتبقى أحسن 🌱',
      'فيه هدوء نفسي لطيف 😌',
      'اليوم مر بشكل مريح 🙂',
    ],
    insight: 'أنتِ بتحاولي تشوفي الجانب المريح حتى في الأيام العادية.',
    advice: 'متقلقيش من البطء… التقدم الهادئ مهم.',
    routine: ['قراءة بسيطة', 'كتابة أفكار', 'وقت راحة', 'تقليل التفكير الزائد'],
    supportMessage: 'كل حاجة بتيجي في وقتها 🤍',
    dayDescriptionFusha: ['أشعر بأن الأمور ستتحسن', 'ثمة هدوء نفسي لطيف', 'مر اليوم بشكل مريح'],
    insightFusha: 'أنت تحاولين رؤية الجانب المريح حتى في الأيام العادية.',
    adviceFusha: 'لا تقلقي من البطء... التقدم الهادئ مهم.',
    routineFusha: ['قراءة بسيطة', 'كتابة أفكار', 'وقت راحة', 'تقليل التفكير الزائد'],
    supportMessageFusha: 'كل شيء يأتي في وقته',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'neutral', 'overwhelmed', 'calm'},
    matchInfluences: {'work', 'sleep'},
    dayDescription: [
      'عندي إرهاق خفيف لكن مسيطرة 😌',
      'اليوم مر بشكل عادي 😶',
      'محتاجة راحة أكتر 🤯',
    ],
    insight: 'أنتِ مش سيئة نفسيًا لكن جسمك وعقلك محتاجين تهدئة.',
    advice: 'الراحة جزء مهم من الإنتاجية.',
    routine: ['تقليل المهام', 'ميه كفاية', 'راحة بدون ذنب', 'نوم أبكر'],
    supportMessage: 'أحيانًا أهدى أيامنا بتكون الأكثر احتياجًا للراحة 🤍',
    dayDescriptionFusha: ['لدي إرهاق خفيف لكنني مسيطرة', 'مر اليوم بشكل عادي', 'أحتاج إلى راحة أكثر'],
    insightFusha: 'أنت لست في حالة سيئة نفسيا لكن جسدك وعقلك يحتاجان إلى التهدئة.',
    adviceFusha: 'الراحة جزء مهم من الإنتاجية.',
    routineFusha: ['تقليل المهام', 'شرب ماء كافٍ', 'راحة دون شعور بالذنب', 'نوم أبكر'],
    supportMessageFusha: 'أحيانا تكون أهدأ أيامنا الأكثر احتياجا للراحة',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'calm', 'hopeful', 'grateful'},
    matchInfluences: {'gratitude', 'nature'},
    dayDescription: [
      'ممتنة للحاجات الصغيرة 🤍',
      'الجو مريحني نفسيًا 🌱',
      'فيه سلام داخلي بسيط 😌',
    ],
    insight: 'أنتِ قادرة تلاقي راحة حتى في التفاصيل الصغيرة.',
    advice: 'استمري في تقدير اللحظات الهادية.',
    routine: ['كتابة امتنان', 'قعدة في مكان هادي', 'موسيقى مريحة', 'تنفس ببطء'],
    supportMessage: 'القلب الهادي يرتاح بالحاجات البسيطة 🤍',
    dayDescriptionFusha: ['ممتنة للأشياء الصغيرة', 'الطقس أراحني نفسيا', 'ثمة سلام داخلي بسيط'],
    insightFusha: 'أنت قادرة على إيجاد الراحة حتى في التفاصيل الصغيرة.',
    adviceFusha: 'استمري في تقدير اللحظات الهادئة.',
    routineFusha: ['كتابة الامتنان', 'جلسة في مكان هادئ', 'موسيقى مريحة', 'تنفس ببطء'],
    supportMessageFusha: 'القلب الهادئ يرتاح بالأشياء البسيطة',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'content', 'calm', 'hopeful'},
    matchInfluences: {'hobby', 'routine'},
    dayDescription: [
      'ممارسة حاجة بحبها حسنت يومي 🙂',
      'فيه هدوء وطاقة خفيفة 🌱',
      'يوم بسيط لكنه لطيف 😌',
    ],
    insight: 'الهوايات والروتين المريح بيأثروا على نفسيتك بشكل واضح.',
    advice: 'خلي لنفسك وقت ثابت للحاجات اللي بتحبيها.',
    routine: ['ممارسة هواية', 'تقليل الضغط', 'وقت بدون موبايل', 'مشروب بتحبيه'],
    supportMessage: 'أنتِ تستحقي أيام هادية ومريحة 🤍',
    dayDescriptionFusha: ['ممارسة شيء أحبه حسنت يومي', 'ثمة هدوء وطاقة خفيفة', 'يوم بسيط لكنه لطيف'],
    insightFusha: 'الهوايات والروتين المريح يؤثران على نفسيتك بشكل واضح.',
    adviceFusha: 'خصصي لنفسك وقتا ثابتا للأشياء التي تحبينها.',
    routineFusha: ['ممارسة هواية', 'تقليل الضغط', 'وقت بدون هاتف', 'مشروب تحبينه'],
    supportMessageFusha: 'أنت تستحقين أياما هادئة ومريحة',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'neutral', 'loved', 'calm'},
    matchInfluences: {'relationships', 'friends'},
    dayDescription: [
      'الناس المريحة خلت يومي ألطف 🥰',
      'مفيش مشاعر قوية لكن فيه راحة 😶',
      'حاسة بهدوء نفسي 😌',
    ],
    insight: 'الاهتمام البسيط من الناس بيفرق معاكِ جدًا.',
    advice: 'متبعديش عن الأشخاص اللي بيريحوكي نفسيًا.',
    routine: ['مكالمة مع شخص قريب', 'قعدة خفيفة', 'تقليل العزلة', 'نوم منتظم'],
    supportMessage: 'وجود ناس حلوة حوالينا يهون أيام كتير 🤍',
    dayDescriptionFusha: ['الأشخاص المريحون جعلوا يومي أجمل', 'لا مشاعر قوية لكن ثمة راحة', 'أشعر بهدوء نفسي'],
    insightFusha: 'الاهتمام البسيط من الآخرين يحدث فارقا كبيرا معك.',
    adviceFusha: 'لا تبتعدي عن الأشخاص الذين يريحونك نفسيا.',
    routineFusha: ['مكالمة مع شخص قريب', 'جلسة خفيفة', 'تقليل العزلة', 'نوم منتظم'],
    supportMessageFusha: 'وجود أشخاص طيبين من حولنا يهون أياما كثيرة',
  ),
  ReflectionScenario(
    moodId: 'okay',
    matchFeelings: {'content', 'neutral', 'grateful'},
    matchInfluences: {'routine', 'health'},
    dayDescription: [
      'جسمي أهدى من الأيام اللي فاتت 🙂',
      'اليوم مستقر بشكل بسيط 😶',
      'ممتنة لأي لحظة راحة 🤍',
    ],
    insight: 'أنتِ محتاجة استقرار وراحة أكتر من الحماس الكبير.',
    advice: 'اسمعي لجسمك ومتهمليش راحتك.',
    routine: ['أكل خفيف', 'ميه كفاية', 'راحة وقت التعب', 'نوم منتظم'],
    supportMessage: 'الاستقرار البسيط يعتبر إنجاز أحيانًا 🤍',
    dayDescriptionFusha: ['جسدي أكثر هدوءا من الأيام الماضية', 'كان يومي مستقرا بشكل بسيط', 'ممتنة لأي لحظة راحة'],
    insightFusha: 'أنت بحاجة إلى الاستقرار والراحة أكثر من الحماس الكبير.',
    adviceFusha: 'استمعي إلى جسدك ولا تهملي راحتك.',
    routineFusha: ['أكل خفيف', 'شرب ماء كافٍ', 'راحة عند التعب', 'نوم منتظم'],
    supportMessageFusha: 'الاستقرار البسيط يعد إنجازا أحيانا',
  ),

  // ═══════════ ليست جيدة 😔 ═══════════
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'overwhelmed', 'anxious', 'guilty'},
    matchInfluences: {'work', 'inner_voice'},
    dayDescription: [
      'عقلي مش بيسكت وده مرهقني 😟',
      'حاسة إني مضغوطة طول الوقت 🤯',
      'بلوم نفسي على أقل حاجة 😔',
    ],
    insight: 'أنتِ تحت ضغط ذهني مستمر وبتحملي نفسك فوق طاقتها.',
    advice: 'عاملي نفسك بنفس اللطف اللي بتعاملي بيه غيرك.',
    routine: ['كتابة الأفكار', 'تقليل المهام', 'وقت راحة', 'نوم أبكر'],
    supportMessage: 'مش لازم تكوني قوية طول الوقت 🤍',
    dayDescriptionFusha: ['عقلي لا يهدأ وهذا يرهقني', 'أشعر بالضغط طوال الوقت', 'ألوم نفسي على أقل شيء'],
    insightFusha: 'أنت تحت ضغط ذهني مستمر وتحملين نفسك فوق طاقتها.',
    adviceFusha: 'تعاملي مع نفسك بنفس اللطف الذي تعاملين به الآخرين.',
    routineFusha: ['كتابة الأفكار', 'تقليل المهام', 'وقت راحة', 'نوم أبكر'],
    supportMessageFusha: 'ليس من الضروري أن تكوني قوية طوال الوقت',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'lonely', 'sad', 'scared'},
    matchInfluences: {'relationships', 'social_media'},
    dayDescription: [
      'الوحدة تقيلة على قلبي 💔',
      'حاسة بخوف وحزن جوايا 😢',
      'المقارنة مأثرة على نفسيتي 😨',
    ],
    insight: 'أنتِ محتاجة احتواء وراحة نفسية أكتر من أي حلول.',
    advice: 'ابعدي شوية عن أي حاجة بتزود الضغط النفسي.',
    routine: ['تقليل السوشيال ميديا', 'مشاهدة شيء مريح', 'مكالمة مع شخص آمن', 'مشروب دافي'],
    supportMessage: 'وجودك مهم حتى وأنتِ تعبانة 🤍',
    dayDescriptionFusha: ['الوحدة ثقيلة على قلبي', 'أشعر بخوف وحزن بداخلي', 'المقارنة تؤثر على نفسيتي'],
    insightFusha: 'أنت بحاجة إلى احتواء وراحة نفسية أكثر من أي حلول.',
    adviceFusha: 'ابتعدي قليلا عن أي شيء يزيد الضغط النفسي.',
    routineFusha: ['تقليل وسائل التواصل الاجتماعي', 'مشاهدة شيء مريح', 'مكالمة مع شخص آمن', 'مشروب دافئ'],
    supportMessageFusha: 'وجودك مهم حتى وأنت تعانين',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'angry', 'frustrated', 'exhausted'},
    matchInfluences: {'conflict', 'work'},
    dayDescription: [
      'الضغط متراكم فوقي 😠',
      'حاسة بإحباط كبير 😤',
      'حتى جسمي محتاج راحة 🥵',
    ],
    insight: 'أنتِ في حالة إنهاك نفسي وجسدي واضحة.',
    advice: 'قبل ما تحاولي تحلي كل حاجة… ارتاحي الأول.',
    routine: ['حمام دافي', 'أكل خفيف', 'راحة من النقاشات', 'نوم كفاية'],
    supportMessage: 'أنتِ مش ضعيفة… أنتِ فقط مرهقة 🤍',
    dayDescriptionFusha: ['الضغط متراكم علي', 'أشعر بإحباط كبير', 'حتى جسدي يحتاج إلى راحة'],
    insightFusha: 'أنت في حالة إنهاك نفسي وجسدي واضحة.',
    adviceFusha: 'قبل أن تحاولي حل كل شيء... استريحي أولا.',
    routineFusha: ['حمام دافئ', 'أكل خفيف', 'راحة من النقاشات', 'نوم كافٍ'],
    supportMessageFusha: 'أنت لست ضعيفة... أنت فقط مرهقة',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'overwhelmed', 'calm', 'sad'},
    matchInfluences: {'health', 'sleep'},
    dayDescription: [
      'جسمي مستنزف نفسيًا وجسديًا 🤯',
      'حتى الحاجات البسيطة محتاجة مجهود 😔',
      'التعب مأثر على مودّي 😢',
    ],
    insight: 'التعب الجسدي مأثر بشكل واضح على نفسيتك.',
    advice: 'جسمك محتاج راحة مش ضغط زيادة.',
    routine: ['سوائل دافية', 'أكل مغذي', 'تقليل المهام', 'راحة كفاية'],
    supportMessage: 'كوني لطيفة مع نفسك النهارده 🤍',
    dayDescriptionFusha: ['جسدي مستنزف نفسيا وجسديا', 'حتى الأشياء البسيطة تحتاج إلى جهد', 'التعب يؤثر على مزاجي'],
    insightFusha: 'التعب الجسدي يؤثر على نفسيتك.',
    adviceFusha: 'جسدك يحتاج إلى راحة لا إلى مزيد من الضغط.',
    routineFusha: ['سوائل دافئة', 'أكل مغذٍّ', 'تقليل المهام', 'راحة كافية'],
    supportMessageFusha: 'كوني لطيفة مع نفسك اليوم',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'anxious', 'hopeless', 'guilty'},
    matchInfluences: {'inner_voice', 'relationships'},
    dayDescription: [
      'صوتي الداخلي قاسي عليا 😔',
      'حاسة إني مكسورة نفسيًا 😞',
      'القلق واخد مساحة كبيرة 😟',
    ],
    insight: 'أنتِ محتاجة تهوني على نفسك بدل ما تضغطيها.',
    advice: 'مش كل فكرة في دماغك حقيقة.',
    routine: ['كتابة المشاعر', 'تنفس ببطء', 'تقليل التفكير قبل النوم', 'سماع شيء مريح'],
    supportMessage: 'حتى أصعب المشاعر بتمر 🤍',
    dayDescriptionFusha: ['صوتي الداخلي قاسٍ علي', 'أشعر بأنني مكسورة نفسيا', 'القلق يأخذ مساحة كبيرة'],
    insightFusha: 'أنت بحاجة إلى أن تخففي على نفسك بدلا من الضغط عليها.',
    adviceFusha: 'ليست كل فكرة في ذهنك حقيقية.',
    routineFusha: ['كتابة المشاعر', 'تنفس ببطء', 'تقليل التفكير قبل النوم', 'الاستماع إلى شيء مريح'],
    supportMessageFusha: 'حتى أصعب المشاعر تمر',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'lonely', 'overwhelmed', 'calm'},
    matchInfluences: {'relationships', 'routine'},
    dayDescription: [
      'حاسة بوحدة رغم هدوء اليوم 💔',
      'طاقتي أقل من المعتاد 🤯',
      'بحاول أعدي اليوم بهدوء 😔',
    ],
    insight: 'أنتِ محتاجة دعم نفسي واحتواء بسيط.',
    advice: 'متنعزليش وقت التعب.',
    routine: ['مكالمة مع حد قريب', 'أكل بتحبيه', 'وقت بعيد عن الضغط', 'نوم بدري'],
    supportMessage: 'أنتِ تستحقي الاحتواء والراحة 🤍',
    dayDescriptionFusha: ['أشعر بالوحدة رغم هدوء اليوم', 'طاقتي أقل من المعتاد', 'أحاول أن أتجاوز اليوم بهدوء'],
    insightFusha: 'أنت بحاجة إلى دعم نفسي واحتواء بسيط.',
    adviceFusha: 'لا تعتزلي وقت التعب.',
    routineFusha: ['مكالمة مع شخص قريب', 'طعام تحبينه', 'وقت بعيد عن الضغط', 'نوم مبكر'],
    supportMessageFusha: 'أنت تستحقين الاحتواء والراحة',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'frustrated', 'anxious', 'overwhelmed'},
    matchInfluences: {'work', 'future'},
    dayDescription: [
      'التفكير في المستقبل مقلقني 😟',
      'حاسة إن الضغط أكبر مني 😤',
      'عقلي مرهق جدًا 🤯',
    ],
    insight: 'التفكير الزائد مستنزف طاقتك النفسية.',
    advice: 'ركزي على خطوة واحدة فقط دلوقتي.',
    routine: ['تقسيم المهام', 'تقليل الضغط', 'كتابة الأولويات', 'راحة بين المهام'],
    supportMessage: 'مش لازم تحلي كل حاجة مرة واحدة 🤍',
    dayDescriptionFusha: ['التفكير في المستقبل يقلقني', 'أشعر بأن الضغط أكبر مني', 'عقلي مرهق جدا'],
    insightFusha: 'التفكير الزائد يستنزف طاقتك النفسية.',
    adviceFusha: 'ركزي على خطوة واحدة فقط الآن.',
    routineFusha: ['تقسيم المهام', 'تقليل الضغط', 'كتابة الأولويات', 'راحة بين المهام'],
    supportMessageFusha: 'ليس من الضروري أن تحلي كل شيء دفعة واحدة',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'sad', 'calm', 'scared'},
    matchInfluences: {'news', 'social_media'},
    dayDescription: [
      'الأخبار مأثرة على نفسيتي 😢',
      'حاسة بخوف داخلي 😨',
      'مودّي أهدى لكنه حزين 😔',
    ],
    insight: 'أنتِ متأثرة بالطاقة السلبية اللي حواليك.',
    advice: 'خدي بريك من أي محتوى متعب نفسيًا.',
    routine: ['تقليل الأخبار', 'موسيقى مريحة', 'وقت هدوء', 'شرب ميه كفاية'],
    supportMessage: 'قلبك محتاج هدوء أكتر من أي حاجة 🤍',
    dayDescriptionFusha: ['الأخبار تؤثر على نفسيتي', 'أشعر بخوف داخلي', 'مزاجي أهدأ لكنه حزين'],
    insightFusha: 'أنت متأثرة بالطاقة السلبية من حولك.',
    adviceFusha: 'خذي استراحة من أي محتوى يرهق نفسيتك.',
    routineFusha: ['تقليل متابعة الأخبار', 'موسيقى مريحة', 'وقت هدوء', 'شرب ماء كافٍ'],
    supportMessageFusha: 'قلبك يحتاج إلى هدوء أكثر من أي شيء',
  ),
  ReflectionScenario(
    moodId: 'not_good',
    matchFeelings: {'exhausted', 'frustrated', 'sad'},
    matchInfluences: {'period', 'body'},
    dayDescription: [
      'هرموناتي مأثرة على مودّي جدًا 🌸',
      'نفسيتي أضعف من المعتاد 😢',
      'جسمي وعقلي محتاجين راحة 🥵',
    ],
    insight: 'أنتِ متأثرة جسديًا وهرمونيًا وده طبيعي جدًا.',
    advice: 'خففي توقعاتك من نفسك في الأيام دي.',
    routine: ['مشروب دافي', 'شوكولاتة أو أكل مريح', 'بطانية وفيلم هادي', 'نوم كفاية'],
    supportMessage: 'مشاعرك الحالية حقيقية ومفهومة جدًا 🤍',
    dayDescriptionFusha: ['هرموناتي تؤثر على مزاجي كثيرا', 'نفسيتي أضعف من المعتاد', 'جسدي وعقلي يحتاجان إلى راحة'],
    insightFusha: 'أنت متأثرة جسديا وهرمونيا وهذا طبيعي جدا.',
    adviceFusha: 'خففي توقعاتك من نفسك في هذه الأيام.',
    routineFusha: ['مشروب دافئ', 'شوكولاتة أو طعام مريح', 'بطانية وفيلم هادئ', 'نوم كافٍ'],
    supportMessageFusha: 'مشاعرك الحالية حقيقية ومفهومة جدا',
  ),

  // ═══════════ سيئة 😢 ═══════════
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'sad', 'lonely', 'scared'},
    matchInfluences: {'relationships', 'social_media'},
    dayDescription: [
      'حاسة بثقل وحزن طول اليوم 😭',
      'الوحدة مأثرة على قلبي جدًا 💔',
      'فيه خوف وقلق مش قادرين يهدوا 😨',
    ],
    insight: 'أنتِ مستنزفة نفسيًا ومحتاجة أمان واحتواء أكتر من أي نصيحة.',
    advice: 'ابعدي شوية عن أي حاجة بتزود المقارنة أو التوتر.',
    routine: ['إغلاق السوشيال ميديا لفترة', 'مشروب دافي', 'حضن أو مكالمة مريحة', 'نوم بدري'],
    supportMessage: 'أعرف إنك تعبانة… لكنك تستحقي الرحمة مش القسوة 🤍',
    dayDescriptionFusha: ['أشعر بثقل وحزن طوال اليوم', 'الوحدة تؤثر على قلبي كثيرا', 'ثمة خوف وقلق لا يهدآن'],
    insightFusha: 'أنت مستنزفة نفسيا وتحتاجين إلى أمان واحتواء أكثر من أي نصيحة.',
    adviceFusha: 'ابتعدي قليلا عن أي شيء يزيد المقارنة أو التوتر.',
    routineFusha: ['إغلاق وسائل التواصل لفترة', 'مشروب دافئ', 'عناق أو مكالمة مريحة', 'نوم مبكر'],
    supportMessageFusha: 'أعلم أنك تعانين... لكنك تستحقين الرحمة لا القسوة',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'angry', 'frustrated', 'exhausted'},
    matchInfluences: {'conflict', 'work'},
    dayDescription: [
      'كل حاجة فوق طاقتي 😠',
      'الإحباط مسيطر عليا 😤',
      'حتى جسمي محتاج راحة 🥵',
    ],
    insight: 'أنتِ في مرحلة ضغط نفسي وجسدي كبيرة.',
    advice: 'مش لازم تصلحي كل حاجة في يوم واحد.',
    routine: ['حمام دافي', 'وجبة خفيفة', 'راحة من النقاشات', 'نوم كفاية'],
    supportMessage: 'أنتِ مش فاشلة… أنتِ فقط مرهقة جدًا 🤍',
    dayDescriptionFusha: ['كل شيء فوق طاقتي', 'الإحباط مسيطر علي', 'حتى جسدي يحتاج إلى راحة'],
    insightFusha: 'أنت في مرحلة ضغط نفسي وجسدي كبيرة.',
    adviceFusha: 'ليس من الضروري أن تصلحي كل شيء في يوم واحد.',
    routineFusha: ['حمام دافئ', 'وجبة خفيفة', 'راحة من النقاشات', 'نوم كافٍ'],
    supportMessageFusha: 'أنت لست فاشلة... أنت فقط مرهقة جدا',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'hopeless', 'guilty', 'anxious'},
    matchInfluences: {'inner_voice', 'relationships'},
    dayDescription: [
      'صوتي الداخلي قاسي عليا 😔',
      'حاسة بخوف وتوتر طول الوقت 😟',
      'قلبي متعب ومش قادرة أهدى 😞',
    ],
    insight: 'أنتِ بتمري بحالة حساسة نفسيًا ومحتاجة تهوني على نفسك.',
    advice: 'مش كل فكرة سلبية حقيقية.',
    routine: ['كتابة مشاعرك', 'تقليل التفكير قبل النوم', 'تنفس ببطء', 'سماع شيء مريح'],
    supportMessage: 'حتى أصعب المشاعر بتمر… ومش لازم تعديها لوحدك 🤍',
    dayDescriptionFusha: ['صوتي الداخلي قاسٍ علي', 'أشعر بخوف وتوتر طوال الوقت', 'قلبي متعب ولا أستطيع الهدوء'],
    insightFusha: 'أنت تمرين بحالة حساسة نفسيا وتحتاجين إلى أن تخففي على نفسك.',
    adviceFusha: 'ليست كل فكرة سلبية حقيقية.',
    routineFusha: ['كتابة مشاعرك', 'تقليل التفكير قبل النوم', 'تنفس ببطء', 'الاستماع إلى شيء مريح'],
    supportMessageFusha: 'حتى أصعب المشاعر تمر... وليس من الضروري أن تعيشيها وحدك',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'exhausted', 'sad', 'overwhelmed'},
    matchInfluences: {'health', 'body'},
    dayDescription: [
      'جسمي مستنزف جدًا 🥵',
      'التعب مأثر على نفسيتي 😢',
      'حتى أبسط الحاجات محتاجة مجهود 🤯',
    ],
    insight: 'الإرهاق الجسدي مأثر على مشاعرك بشكل واضح.',
    advice: 'جسمك محتاج احتواء وراحة مش ضغط.',
    routine: ['سوائل دافية', 'أكل مغذي', 'تقليل المهام', 'راحة بدون ذنب'],
    supportMessage: 'كوني حنونة على نفسك النهارده 🤍',
    dayDescriptionFusha: ['جسدي مستنزف جدا', 'التعب يؤثر على نفسيتي', 'حتى أبسط الأشياء تحتاج إلى جهد'],
    insightFusha: 'الإرهاق الجسدي يؤثر على مشاعرك بشكل واضح.',
    adviceFusha: 'جسدك يحتاج إلى احتواء وراحة لا إلى ضغط.',
    routineFusha: ['سوائل دافئة', 'أكل مغذٍّ', 'تقليل المهام', 'راحة دون شعور بالذنب'],
    supportMessageFusha: 'كوني حنونة على نفسك اليوم',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'frustrated', 'scared', 'sad'},
    matchInfluences: {'future', 'work'},
    dayDescription: [
      'التفكير في المستقبل مخوفني 😨',
      'حاسة إن الضغط أكبر مني 😤',
      'الحزن واخد مساحة كبيرة 😢',
    ],
    insight: 'أنتِ تحت ضغط التفكير الزائد والخوف من المجهول.',
    advice: 'ركزي على يومك الحالي بدل كل المستقبل مرة واحدة.',
    routine: ['تقسيم المهام', 'كتابة الأولويات', 'وقت راحة', 'تقليل التفكير ليلًا'],
    supportMessage: 'مش لازم تعرفي كل الإجابات دلوقتي 🤍',
    dayDescriptionFusha: ['التفكير في المستقبل يخيفني', 'أشعر بأن الضغط أكبر مني', 'الحزن يأخذ مساحة كبيرة'],
    insightFusha: 'أنت تحت ضغط التفكير الزائد والخوف من المجهول.',
    adviceFusha: 'ركزي على يومك الحالي بدلا من المستقبل كله دفعة واحدة.',
    routineFusha: ['تقسيم المهام', 'كتابة الأولويات', 'وقت راحة', 'تقليل التفكير ليلا'],
    supportMessageFusha: 'ليس من الضروري أن تعرفي كل الإجابات الآن',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'lonely', 'hopeless', 'overwhelmed'},
    matchInfluences: {'relationships', 'isolation'},
    dayDescription: [
      'حاسة إني لوحدي جدًا 💔',
      'قلبي مكسور ومتعب 😞',
      'طاقتي النفسية منتهية 🤯',
    ],
    insight: 'أنتِ محتاجة احتواء حقيقي وشعور بالأمان.',
    advice: 'حاولي متنعزليش تمامًا وقت التعب.',
    routine: ['مكالمة مع شخص قريب', 'مشاهدة شيء مريح', 'أكل بتحبيه', 'نوم بدري'],
    supportMessage: 'وجودك مهم حتى لو أنتِ مش شايفة ده دلوقتي 🤍',
    dayDescriptionFusha: ['أشعر بأنني وحيدة جدا', 'قلبي مكسور ومتعب', 'طاقتي النفسية نفدت'],
    insightFusha: 'أنت بحاجة إلى احتواء حقيقي وشعور بالأمان.',
    adviceFusha: 'حاولي ألا تعتزلي تماما وقت التعب.',
    routineFusha: ['مكالمة مع شخص قريب', 'مشاهدة شيء مريح', 'طعام تحبينه', 'نوم مبكر'],
    supportMessageFusha: 'وجودك مهم حتى لو لم تري ذلك الآن',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'angry', 'exhausted', 'anxious'},
    matchInfluences: {'conflict', 'inner_voice'},
    dayDescription: [
      'أعصابي مستنزفة جدًا 😠',
      'القلق والتفكير مش مخليني أرتاح 😟',
      'جسمي وعقلي محتاجين هدوء 🥵',
    ],
    insight: 'أنتِ في حالة توتر واستنزاف عصبي.',
    advice: 'ابعدي عن أي نقاش أو ضغط إضافي اليوم.',
    routine: ['تنفس ببطء', 'تقليل الضوضاء', 'حمام دافي', 'راحة بدون موبايل'],
    supportMessage: 'أنتِ محتاجة هدوء أكتر من الحلول دلوقتي 🤍',
    dayDescriptionFusha: ['أعصابي مستنزفة جدا', 'القلق والتفكير لا يتركانني أرتاح', 'جسدي وعقلي يحتاجان إلى هدوء'],
    insightFusha: 'أنت في حالة توتر واستنزاف عصبي.',
    adviceFusha: 'ابتعدي عن أي نقاش أو ضغط إضافي اليوم.',
    routineFusha: ['تنفس ببطء', 'تقليل الضوضاء', 'حمام دافئ', 'راحة بدون هاتف'],
    supportMessageFusha: 'أنت تحتاجين إلى هدوء أكثر من الحلول الآن',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'sad', 'overwhelmed', 'scared'},
    matchInfluences: {'news', 'social_media'},
    dayDescription: [
      'الأخبار مأثرة على مودّي 😢',
      'حاسة بخوف وتوتر داخلي 😨',
      'عقلي مرهق من التفكير 🤯',
    ],
    insight: 'الطاقة السلبية اللي حواليك مأثرة على نفسيتك.',
    advice: 'اعملي بريك من الأخبار والسوشيال شوية.',
    routine: ['موسيقى هادية', 'وقت بعيد عن الشاشة', 'شرب ميه', 'نوم كفاية'],
    supportMessage: 'قلبك محتاج راحة وهدوء 🤍',
    dayDescriptionFusha: ['الأخبار تؤثر على مزاجي', 'أشعر بخوف وتوتر داخلي', 'عقلي مرهق من التفكير'],
    insightFusha: 'الطاقة السلبية من حولك تؤثر على نفسيتك.',
    adviceFusha: 'خذي استراحة من الأخبار ووسائل التواصل لفترة.',
    routineFusha: ['موسيقى هادئة', 'وقت بعيد عن الشاشة', 'شرب ماء', 'نوم كافٍ'],
    supportMessageFusha: 'قلبك يحتاج إلى راحة وهدوء',
  ),
  ReflectionScenario(
    moodId: 'bad',
    matchFeelings: {'exhausted', 'frustrated', 'sad'},
    matchInfluences: {'period', 'body'},
    dayDescription: [
      'هرموناتي مأثرة على نفسيتي جدًا 🌸',
      'نفسيتي أضعف من المعتاد 😢',
      'جسمي محتاج راحة حقيقية 🥵',
    ],
    insight: 'أنتِ متأثرة جسديًا وهرمونيًا وده طبيعي جدًا.',
    advice: 'خففي توقعاتك من نفسك في الأيام دي.',
    routine: ['مشروب دافي', 'بطانية وفيلم مريح', 'أكل بتحبيه', 'نوم كفاية'],
    supportMessage: 'مشاعرك الحالية حقيقية ومفهومة جدًا 🤍',
    dayDescriptionFusha: ['هرموناتي تؤثر على نفسيتي كثيرا', 'نفسيتي أضعف من المعتاد', 'جسدي يحتاج إلى راحة حقيقية'],
    insightFusha: 'أنت متأثرة جسديا وهرمونيا وهذا طبيعي جدا.',
    adviceFusha: 'خففي توقعاتك من نفسك في هذه الأيام.',
    routineFusha: ['مشروب دافئ', 'بطانية وفيلم مريح', 'طعام تحبينه', 'نوم كافٍ'],
    supportMessageFusha: 'مشاعرك الحالية حقيقية ومفهومة جدا',
  ),
];
