name: routiny
description: "Routiny — a calm routine & self-care companion."
publish_to: 'none'
version: 1.1.2+14

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  lottie: ^3.1.3
  just_audio: ^0.9.42
  image_picker: ^1.1.2
  share_plus: ^10.1.4
  google_mobile_ads: 6.0.0
  audio_session: ^0.1.25
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/moods/
    - assets/lottie/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway.ttf
    - family: InterDisplay
      fonts:
        - asset: assets/fonts/inter_display_black.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_black.ttf
